name: Deploy dan-plugin-banking

on:
 push:
   branches: [ main ]
   paths-ignore:
     - '**/README.md'
     - '**/*.yml'
 workflow_dispatch:

jobs:
 run:
  permissions:
    actions: read
    contents: read
  uses: data-altinn-no/deploy-actions/.github/workflows/dan-deploy-flow.yml@d08132e852a68b9e10b759cb30e23366219790b0
  with:
    artifact_name: 'dan-plugin-banking' # Can be omitted, defaults to 'artifact'
    function_project_path: 'src/Altinn.Dan.Plugin.Banking'
  secrets:
    function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
    publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
    azure_artifact_pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}
    azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    resource_group_prod: ${{ secrets.RESOURCE_GROUP_PROD }}
